# Generated by Django 4.2.7 on 2026-04-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Physical or operating address', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Primary support or business phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='GST, VAT, EIN, or equivalent tax registration number', max_length=100, null=True),
        ),
    ]
